language: python
python:
    #- "2.6"    # Fix OrderedDict issue
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install .
before_script:
    - cd test
    - pip install -r test_requirements.txt
script:
    - coverage run test_f90nml.py
    #- python test_f90nml.py
after_success:
    - coveralls
