language: python
python:
    #- "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install: pip install .
script:
    - cd test
    - python test/test_f90nml.py
#branches:
#    only:
#        - master
